### PR TITLE
Use Markdown formatting for README.

### PR DESCRIPTION
**Pull request by andrewshadura**

### CODE REVIEW

**Comment by andrewshadura** [comment]
If you also rename README to README.md, GitHub renders Markdown into pretty-formatted text. But that's not necessary.

**Comment by KostyaSha** [comment]
So i can PR .md -> .adoc conversion? ;)

**Comment by andrewshadura** [comment]
What would be the purpose of that?

**Comment by KostyaSha** [comment]
The same question to you about this PR.

**Pull request merged**
